#Minecraft server properties
#Wed Jun 03 14:59:42 CST 2026
allow-flight=true
allow-nether=true
debug=false
difficulty=3
enable-command-block=false
enable-query=false
enable-rcon=false
force-gamemode=false
gamemode=0
generate-structures=true
generator-settings=
hardcore=false
level-name=world
level-seed=
level-type=DEFAULT
max-build-height=256
max-players=100
max-world-size=29999984
motd=\u00A7b\u00A7l\u2605 \u00A7d\u00A7l\u661F\u7A7A\u5C9B \u00A7b\u00A7l\u2605 \u00A7r \u00A77| \u00A7f\u63A2\u7D22\u65E0\u5C3D\u661F\u6CB3 \u00A78- \u00A73V1.0\n\u00A77>> \u00A7e\u8E0F\u4E0A\u4F60\u7684\u6F02\u6D41\u4E4B\u65C5 \u00A7a[\u70B9\u51FB\u52A0\u5165]
network-compression-threshold=1024
online-mode=false
op-permission-level=4
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
resource-pack=
resource-pack-sha1=
server-ip=
server-port=25565
snooper-enabled=false
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=0
use-native-transport=true
view-distance=10
white-list=false
